In [ ]:
# Standard library
import random

# Third-party libraries
import numpy as np
# Definición de la clase Network

def feedforward(x,bias,weight):
    """Return the output of the network if ``a`` is input."""

    print("w")
    print(weight)
    print("x")
    print(x)
    print("b")
    print(bias)
    for b, w in zip(bias, weight):
        z=np.dot(w, x)+b
        a = sigmoid(z)
    print('a')
    print(a)

    return a

#### Miscellaneous functions
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [ ]:
import numpy as np
sizes = [2,2,1]
num_layers = len(sizes)
#weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]
weights = [np.array([[ 0.00771645, -0.87215412],[-0.8828999 ,  0.91634591]]), np.array([[-0.27296355, -0.16419596]])]
print("weights: w[input neuron,output neuron]  ---  [[w_1,1^2][w_1,2^2]][[w_2,1^2][w_2,2^2]] ---  [[w_1,1^3][w_1,2^3]] [2, 2] [2, 1]")
print(sizes[:-1], sizes[1:]) # [:-1] desde el inicio hasta el ultimo (sin incluirlo) [2,2] (desde el primero sin el ultimo)
print(weights)

#biases = [np.random.randn(y,1) for y in sizes[1:]]
biases = [np.array([[-0.37810527], [ 0.30153513]]), np.array([[0.83487797]])]
print("biases: b[input layer,input neuron] --- [[b_1^2] [b_2^2]] [[b_1^3]] --- [2, 1]")
print(sizes[1:]) # [1:] desde el indice 1 hasta el ultimo [2,1]
print(biases)

weights: w[input neuron,output neuron]  ---  [[w_1,1^2][w_1,2^2]][[w_2,1^2][w_2,2^2]] ---  [[w_1,1^3][w_1,2^3]] [2, 2] [2, 1]
[2, 2] [2, 1]
[array([[ 0.00771645, -0.87215412],
       [-0.8828999 ,  0.91634591]]), array([[-0.27296355, -0.16419596]])]
biases: b[input layer,input neuron] --- [[b_1^2] [b_2^2]] [[b_1^3]] --- [2, 1]
[2, 1]
[array([[-0.37810527],
       [ 0.30153513]]), array([[0.83487797]])]


In [ ]:
print('1. Inicializar los patrones de entrada x con sus respectivos objetivos t:')
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

print('x= \n {}'.format(X))
T = np.array([[1],
             [0],
             [0],
             [1]])

print('t= \n{}'.format(t))
alpha=0.5

1. Inicializar los patrones de entrada x con sus respectivos objetivos t:
x= 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
t= 
[1]


In [ ]:
# 1. Feed-forward: pasar el patron de entrada por todas la capas
dC_db = [np.zeros(b.shape) for b in biases]
dC_dw = [np.zeros(w.shape) for w in weights]

for x,t in zip(X,T):
    print('-------------------------patrón: {}'.format(x))
    print(x)
    print(t)
    #a=feedforward(x,biases,weights)
    a_list = [x] # list to store all the activations, layer by layer
    z_list = [] # list to store all the z vectors, layer by layer

    for b, w in zip(biases, weights):
        z = np.dot(w,a_list[-1].transpose())+b.transpose()
        z_list.append(z)
        a = sigmoid(z)
        a_list.append(a)

    print("a_list = ")
    print(a_list)
    # 2. output error
    C = (0.5*(t-a_list[-1])**2).mean(axis=0) #indice [-1] significa el último elemento de la lista, correspondiente a la última capa
    print('C = {}'.format(C))

    # 3. back propagation
    delta_list = []
    print(z_list)
    # 3.1 BP: error de la capa de salida ###############################################################################
    delta_L = -(t-a_list[-1])*sigmoid_prime(z_list[-1]) #delta^L = [delta_1^3]
    #delta_L = -np.dot((t-a_list[-1]),sigmoid_prime(z_list[-1])) #delta^L = [delta_1^3]
    print("delta L = {}".format(delta_L)) # [delta_1^3]
    #delta_list.append(delta_L[0])
    delta_list.insert(0,delta_L[0])
    print(delta_list)
    #  3.2 BP: calcular la actualizacion de los pesos y bias en L
    #dC_dw[-1] = np.dot(delta_list[-1], a_list[-2]) #1x1 1x4 = 1x4
    dC_dw[-1] = delta_list[-1]*a_list[-2]
    print('dc_dw: {}'.format(dC_dw[-1]))
    #dC_dw[-1] = np.dot(delta_L, a_list[-2]) #1x1 1x4 = 1x4

    w_new = weights[-1] - alpha*dC_dw[-1] # 1x2   [w_1,1^3][w_1,2^3] ---> new
    print('new weights: ')
    print(w_new)

    dC_db[-1] = delta_list[-1] #1x1
    print('dc_db: {}'.format(dC_db[-1]))
    b_new = biases[-1].transpose()  - alpha*dC_db[-1]   # [b_1^3] --> new
    print('new bias: ')
    print(b_new)
    biases[-1] = b_new   #1x1
    weights[-1] = w_new  #1x2


    print('3.3 BP: error de la capa oculta') #################################################################################
    delta_l = delta_list[-1]*weights[-1]*sigmoid_prime(z_list[-2]) # 1x1 1x2 o 1x2
    print('delta_l')
    #print(delta_l)
    delta_list.insert(0,delta_l[-1]) # como append, pero agrega el elemento al principio y desplaza los existentes
    #print('delta_list despues de append')
    print(delta_list)

    #print('3.4 BP: calcular los pesos y bias de la capa oculta')
    #print('delta_list: {}'.format(delta_list[-2]))
    #print('a_list: {}'.format(a_list[-3]))
    #dC_dw[-2] = np.matmul(delta_list[-2],a_list[-3]) #1x1 1x4 = 1x4
    dC_dw[-2] = delta_list[-2]*a_list[-3]
    #dC_dw[-2] = delta_list[-2]* a_list[-3] #1x1 1x4 = 1x4
    print('dc_dw: {}'.format(dC_dw[-2]))
    w_new = weights[-2] - alpha*dC_dw[-2] # 2x2   [w_1,1^2][w_1,2^2][w_2,1^2][w_2,2^2] ---> new
    print('new weights: ')
    print(w_new)

    dC_db[-2] = delta_list[-2] #1x1
    print('dc_db: {}'.format(dC_db[-2]))
    #print('biases: {}'.format(biases[-2]))
    b_new = biases[-2].transpose()  - alpha*dC_db[-2]   # [b_1^2] [b_2^2] --> new
    print('new bias: ')
    print(b_new)
    biases[-2] = b_new   #1x1
    weights[-2] = w_new  #1x2



    print("weights despues")
    print(weights)

    print("biases despues")
    print(biases)

-------------------------patrón: [0 0]
[0 0]
[1]
a_list = 
[array([0, 0]), array([[0.40658396, 0.57481775]]), array([[0.65237894]])]
C = [0.0604202]
[array([[-0.37810527,  0.30153513]]), array([[0.62951262]])]
delta L = [[-0.07883373]]
[array([-0.07883373])]
dc_dw: [[-0.03205253 -0.04531503]]
new weights: 
[[-0.25693728 -0.14153845]]
dc_db: [-0.07883373]
new bias: 
[[0.87429484]]
3.3 BP: error de la capa oculta
delta_l
[[0.00488707 0.00272704]]
delta_list despues de append
[array([0.00488707, 0.00272704]), array([-0.07883373])]
3.4 BP: calcular los pesos y bias de la capa oculta
delta_list: [0.00488707 0.00272704]
a_list: [0 0]
dc_dw: [0. 0.]
new weights: 
[[ 0.00771645 -0.87215412]
 [-0.8828999   0.91634591]]
dc_db: [0.00488707 0.00272704]
biases: [[-0.37810527]
 [ 0.30153513]]
new bias: 
[[-0.38054881  0.30017161]]
weights despues
[array([[ 0.00771645, -0.87215412],
       [-0.8828999 ,  0.91634591]]), array([[-0.25693728, -0.14153845]])]
biases despues
[array([[-0.38054881,  0.30017

ValueError: ignored